apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
   local:
     push: false
   artifacts:
     - image: mistfall/client
       context: client
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: 'src/**/*.js'
             dest: .
     - image: mistfall/comments
       context: comments
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: '*.js'
             dest: .
     - image: mistfall/event-bus
       context: event-bus
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: '*.js'
             dest: .
     - image: mistfall/moderation
       context: moderation
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: '*.js'
             dest: .
     - image: mistfall/posts
       context: post
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: '*.js'
             dest: .
     - image: mistfall/query
       context: query
       docker:
         dockerfile: Dockerfile
       sync:
         manual:
           - src: '*.js'
             dest: .
